/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseListMemoResponse,
  ApiResponseMemoResponse,
  ApiResponseVoid,
  Create,
  DeleteMemosParams,
  GetMemosParams,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 해당 날짜에 등록된 내 메모 리스트를 조회합니다.
 * @summary 메모 조회
 */
export const getMemos = (
  params: GetMemosParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseListMemoResponse>(
    { url: `/daily-memo`, method: 'GET', params, signal },
    options,
  );
};

export const getGetMemosQueryKey = (params?: GetMemosParams) => {
  return [`/daily-memo`, ...(params ? [params] : [])] as const;
};

export const getGetMemosQueryOptions = <
  TData = Awaited<ReturnType<typeof getMemos>>,
  TError = ErrorType<unknown>,
>(
  params: GetMemosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemos>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMemosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemos>>> = ({ signal }) =>
    getMemos(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMemos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMemosQueryResult = NonNullable<Awaited<ReturnType<typeof getMemos>>>;
export type GetMemosQueryError = ErrorType<unknown>;

export function useGetMemos<
  TData = Awaited<ReturnType<typeof getMemos>>,
  TError = ErrorType<unknown>,
>(
  params: GetMemosParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemos>>,
          TError,
          Awaited<ReturnType<typeof getMemos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMemos<
  TData = Awaited<ReturnType<typeof getMemos>>,
  TError = ErrorType<unknown>,
>(
  params: GetMemosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemos>>,
          TError,
          Awaited<ReturnType<typeof getMemos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMemos<
  TData = Awaited<ReturnType<typeof getMemos>>,
  TError = ErrorType<unknown>,
>(
  params: GetMemosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemos>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 메모 조회
 */

export function useGetMemos<
  TData = Awaited<ReturnType<typeof getMemos>>,
  TError = ErrorType<unknown>,
>(
  params: GetMemosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemos>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMemosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 날짜에 새로운 메모를 생성합니다. (최대 5개 제한)
 * @summary 메모 생성
 */
export const createMemo = (
  create: BodyType<Create>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseMemoResponse>(
    {
      url: `/daily-memo`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: create,
      signal,
    },
    options,
  );
};

export const getCreateMemoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMemo>>,
    TError,
    { data: BodyType<Create> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMemo>>,
  TError,
  { data: BodyType<Create> },
  TContext
> => {
  const mutationKey = ['createMemo'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMemo>>,
    { data: BodyType<Create> }
  > = (props) => {
    const { data } = props ?? {};

    return createMemo(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMemoMutationResult = NonNullable<Awaited<ReturnType<typeof createMemo>>>;
export type CreateMemoMutationBody = BodyType<Create>;
export type CreateMemoMutationError = ErrorType<unknown>;

/**
 * @summary 메모 생성
 */
export const useCreateMemo = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createMemo>>,
      TError,
      { data: BodyType<Create> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createMemo>>,
  TError,
  { data: BodyType<Create> },
  TContext
> => {
  const mutationOptions = getCreateMemoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 메모들을 한 번에 삭제합니다.<br> 스웨거 테스트 할 땐 ids 한 칸에 id 하나만 입력해 주세요. 여러 개 입력하실 경우 Add integer item으로 추가하시면 됩니다.
 * @summary 메모 다중 삭제
 */
export const deleteMemos = (
  params: DeleteMemosParams,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseVoid>({ url: `/daily-memo`, method: 'DELETE', params }, options);
};

export const getDeleteMemosMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMemos>>,
    TError,
    { params: DeleteMemosParams },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMemos>>,
  TError,
  { params: DeleteMemosParams },
  TContext
> => {
  const mutationKey = ['deleteMemos'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMemos>>,
    { params: DeleteMemosParams }
  > = (props) => {
    const { params } = props ?? {};

    return deleteMemos(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMemosMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMemos>>>;

export type DeleteMemosMutationError = ErrorType<unknown>;

/**
 * @summary 메모 다중 삭제
 */
export const useDeleteMemos = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMemos>>,
      TError,
      { params: DeleteMemosParams },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMemos>>,
  TError,
  { params: DeleteMemosParams },
  TContext
> => {
  const mutationOptions = getDeleteMemosMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
