/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseConditionResponse,
  ApiResponseVoid,
  ConditionCreate,
  ConditionUpdate,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 신체(Energy) 점수와 정신(Focus) 점수를 한 세트로 기록합니다. 점수는 각각 0~6 사이로 입력합니다.
 * @summary 컨디션 입력
 */
export const createCondition = (
  conditionCreate: BodyType<ConditionCreate>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseConditionResponse>(
    {
      url: `/conditions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: conditionCreate,
      signal,
    },
    options,
  );
};

export const getCreateConditionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCondition>>,
    TError,
    { data: BodyType<ConditionCreate> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCondition>>,
  TError,
  { data: BodyType<ConditionCreate> },
  TContext
> => {
  const mutationKey = ['createCondition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCondition>>,
    { data: BodyType<ConditionCreate> }
  > = (props) => {
    const { data } = props ?? {};

    return createCondition(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateConditionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCondition>>
>;
export type CreateConditionMutationBody = BodyType<ConditionCreate>;
export type CreateConditionMutationError = ErrorType<unknown>;

/**
 * @summary 컨디션 입력
 */
export const useCreateCondition = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCondition>>,
      TError,
      { data: BodyType<ConditionCreate> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCondition>>,
  TError,
  { data: BodyType<ConditionCreate> },
  TContext
> => {
  const mutationOptions = getCreateConditionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 인증된 사용자의 컨디션 기록 세트를 조회합니다. 본인의 컨디션 기록만 조회할 수 있습니다.
 * @summary 컨디션 조회
 */
export const getCondition = (
  conditionId: number,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseConditionResponse>(
    { url: `/conditions/${conditionId}`, method: 'GET', signal },
    options,
  );
};

export const getGetConditionQueryKey = (conditionId?: number) => {
  return [`/conditions/${conditionId}`] as const;
};

export const getGetConditionQueryOptions = <
  TData = Awaited<ReturnType<typeof getCondition>>,
  TError = ErrorType<unknown>,
>(
  conditionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCondition>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConditionQueryKey(conditionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCondition>>> = ({ signal }) =>
    getCondition(conditionId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!conditionId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCondition>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConditionQueryResult = NonNullable<Awaited<ReturnType<typeof getCondition>>>;
export type GetConditionQueryError = ErrorType<unknown>;

export function useGetCondition<
  TData = Awaited<ReturnType<typeof getCondition>>,
  TError = ErrorType<unknown>,
>(
  conditionId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCondition>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCondition>>,
          TError,
          Awaited<ReturnType<typeof getCondition>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCondition<
  TData = Awaited<ReturnType<typeof getCondition>>,
  TError = ErrorType<unknown>,
>(
  conditionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCondition>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCondition>>,
          TError,
          Awaited<ReturnType<typeof getCondition>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCondition<
  TData = Awaited<ReturnType<typeof getCondition>>,
  TError = ErrorType<unknown>,
>(
  conditionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCondition>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 컨디션 조회
 */

export function useGetCondition<
  TData = Awaited<ReturnType<typeof getCondition>>,
  TError = ErrorType<unknown>,
>(
  conditionId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCondition>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConditionQueryOptions(conditionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 기존에 입력한 컨디션 기록 세트를 삭제합니다.
 * @summary 컨디션 삭제
 */
export const deleteCondition = (
  conditionId: number,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseVoid>(
    { url: `/conditions/${conditionId}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteConditionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCondition>>,
    TError,
    { conditionId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCondition>>,
  TError,
  { conditionId: number },
  TContext
> => {
  const mutationKey = ['deleteCondition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCondition>>,
    { conditionId: number }
  > = (props) => {
    const { conditionId } = props ?? {};

    return deleteCondition(conditionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteConditionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCondition>>
>;

export type DeleteConditionMutationError = ErrorType<unknown>;

/**
 * @summary 컨디션 삭제
 */
export const useDeleteCondition = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCondition>>,
      TError,
      { conditionId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCondition>>,
  TError,
  { conditionId: number },
  TContext
> => {
  const mutationOptions = getDeleteConditionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 기존에 입력한 신체(Energy) 점수와 정신(Focus) 점수를 수정합니다. 점수는 각각 0~6 사이로 입력합니다.
 * @summary 컨디션 수정
 */
export const updateCondition = (
  conditionId: number,
  conditionUpdate: BodyType<ConditionUpdate>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseConditionResponse>(
    {
      url: `/conditions/${conditionId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: conditionUpdate,
    },
    options,
  );
};

export const getUpdateConditionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCondition>>,
    TError,
    { conditionId: number; data: BodyType<ConditionUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCondition>>,
  TError,
  { conditionId: number; data: BodyType<ConditionUpdate> },
  TContext
> => {
  const mutationKey = ['updateCondition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCondition>>,
    { conditionId: number; data: BodyType<ConditionUpdate> }
  > = (props) => {
    const { conditionId, data } = props ?? {};

    return updateCondition(conditionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateConditionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCondition>>
>;
export type UpdateConditionMutationBody = BodyType<ConditionUpdate>;
export type UpdateConditionMutationError = ErrorType<unknown>;

/**
 * @summary 컨디션 수정
 */
export const useUpdateCondition = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCondition>>,
      TError,
      { conditionId: number; data: BodyType<ConditionUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCondition>>,
  TError,
  { conditionId: number; data: BodyType<ConditionUpdate> },
  TContext
> => {
  const mutationOptions = getUpdateConditionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
