/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface AlarmSettingRequestDto {
  is_schedule_end_alarm_on?: boolean;
  is_condition_record_alarm_on?: boolean;
  is_recommend_alarm_on?: boolean;
}
