/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { GetBiorhythm } from './getBiorhythm';

export interface ApiResponseGetBiorhythm {
  success?: boolean;
  message?: string;
  data?: GetBiorhythm;
}
