/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ConditionRecommendationResponse } from './conditionRecommendationResponse';

export interface ApiResponseConditionRecommendationResponse {
  success?: boolean;
  message?: string;
  data?: ConditionRecommendationResponse;
}
