/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { MemoResponse } from './memoResponse';

export interface ApiResponseMemoResponse {
  success?: boolean;
  message?: string;
  data?: MemoResponse;
}
