/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { MeasurementRecordResponse } from './measurementRecordResponse';

export interface ApiResponseMeasurementRecordResponse {
  success?: boolean;
  message?: string;
  data?: MeasurementRecordResponse;
}
