/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface AverageItem {
  period_start?: string;
  period_end?: string;
  label?: string;
  final_condition_score_average?: number;
  body_score_percent_average?: number;
  mind_score_percent_average?: number;
  sleep_score_average?: number;
  sleep_duration_minutes_average?: number;
}
