/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface AverageItem {
  period_start?: string;
  period_end?: string;
  label?: string;
  final_condition_score_average?: number;
  body_score_percent_average?: number;
  mind_score_percent_average?: number;
  sleep_score_average?: number;
  sleep_duration_minutes_average?: number;
  /** Body 평균 점수 기반 상태 문구 */
  body_comment?: string;
  /** Mind 평균 점수 기반 상태 문구 */
  mind_comment?: string;
  /** 평균 수면 시간 기반 상태 문구 */
  sleep_comment?: string;
}
