/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface BiorhythmRequest {
  /**
   * @minLength 24
   * @maxLength 24
   * @pattern ^[01]{24}$
   */
  focused_timeline: string;
  /**
   * @minLength 24
   * @maxLength 24
   * @pattern ^[01]{24}$
   */
  drowsy_timeline: string;
  /**
   * @minLength 24
   * @maxLength 24
   * @pattern ^[01]{24}$
   */
  sleep_timeline: string;
}
