/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

/**
 * 컨디션 기반 추천 일정
 */
export interface ConditionRecommendationItem {
  recommend_id?: number;
  /** 추천 원본 일정 ID */
  source_schedule_id?: number;
  title?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  deadline?: string;
  condition_tag?: string;
  /** 컨디션 태그 표시명 */
  condition_tag_label?: string;
  source_type?: string;
  match_tier?: string;
  display_order?: number;
  /** 컨디션 적합도 기반 추천 이유 문구 */
  suitability_message?: string;
  /** 빈 시간과 예상 소요 시간 적합도 기반 추천 이유 문구 */
  time_margin_message?: string;
  recovery_means?: string[];
}
