/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { EmptyTime } from './emptyTime';
import type { SummaryTag } from './summaryTag';
import type { ConditionRecommendationItem } from './conditionRecommendationItem';

export interface ConditionRecommendationResponse {
  date?: string;
  result_type?: string;
  condition_tag?: string;
  condition_tag_label?: string;
  empty_time?: EmptyTime;
  summary_message?: string;
  summary_tags?: SummaryTag[];
  /** 추천 일정 목록 */
  recommendations?: ConditionRecommendationItem[];
}
