/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleSummary } from './scheduleSummary';

export interface DailySchedules {
  date?: string;
  schedules?: ScheduleSummary[];
}
