/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { DailyMessageResponseDtoCondition } from './dailyMessageResponseDtoCondition';

export interface DailyMessageResponseDto {
  date?: string;
  condition?: DailyMessageResponseDtoCondition;
  message?: string;
  is_energy_recorded?: boolean;
  is_sleep_recorded?: boolean;
}
