/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type DeleteMemosParams = {
  /**
   * 삭제할 메모 ID 리스트 (콤마로 구분, 예: 1,2,3)
   */
  ids: number[];
};
