/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type GetAverageRecordsType =
  (typeof GetAverageRecordsType)[keyof typeof GetAverageRecordsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAverageRecordsType = {
  ALL: 'ALL',
  CONDITION: 'CONDITION',
  SLEEP: 'SLEEP',
} as const;
