/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type GetAverageRecordsGroupBy =
  (typeof GetAverageRecordsGroupBy)[keyof typeof GetAverageRecordsGroupBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAverageRecordsGroupBy = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
} as const;
