/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { GetAverageRecordsType } from './getAverageRecordsType';
import type { GetAverageRecordsGroupBy } from './getAverageRecordsGroupBy';

export type GetAverageRecordsParams = {
  from: string;
  to: string;
  /**
   * 조회할 평균 타입
   */
  type: GetAverageRecordsType;
  /**
   * 평균 집계 단위
   */
  groupBy: GetAverageRecordsGroupBy;
};
