/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface GetBiorhythm {
  member_id?: number;
  focused_timeline?: string;
  drowsy_timeline?: string;
  sleep_timeline?: string;
}
