/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type GetConditionRecommendationsParams = {
  /**
   * 추천 대상 날짜 (yyyy-MM-dd)
   */
  date: string;
};
