/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { GetMethodsDefaultMethodsItem } from './getMethodsDefaultMethodsItem';

export interface GetMethods {
  default_methods?: GetMethodsDefaultMethodsItem[];
  custom_methods?: string[];
}
