/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type GetQueueCardRecommendationsParams = {
  /**
   * 탐색 범위(일). 7(기본) 또는 14(확장)
   */
  days?: number;
};
