/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface GoogleLoginRequestDto {
  /** @minLength 1 */
  google_id_token: string;
  /** @minLength 1 */
  device_id: string;
}
