/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { AverageItem } from './averageItem';

export interface MeasurementAverageResponse {
  from?: string;
  to?: string;
  type?: string;
  group_by?: string;
  items?: AverageItem[];
}
