/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { PageResponseConditionRecord } from './pageResponseConditionRecord';
import type { PageResponseSleepRecord } from './pageResponseSleepRecord';

export interface MeasurementRecordResponse {
  date?: string;
  final_condition_score?: number;
  condition_level?: string;
  condition_tag?: string;
  body_score_percent?: number;
  mind_score_percent?: number;
  sleep_score?: number;
  sleep_duration_minutes?: number;
  conditions?: PageResponseConditionRecord;
  sleeps?: PageResponseSleepRecord;
}
