/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ConditionRecord } from './conditionRecord';
import type { PaginationInfo } from './paginationInfo';

export interface PageResponseConditionRecord {
  data?: ConditionRecord[];
  pagination?: PaginationInfo;
}
