/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface PaginationInfo {
  page?: number;
  size?: number;
  total_elements?: number;
  total_pages?: number;
  has_next?: boolean;
  has_previous?: boolean;
}
