/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface RecommendationAcceptResponse {
  recommend_id?: number;
  schedule_id?: number;
  title?: string;
  date?: string;
  start_time?: string;
  end_time?: string;
  source_type?: string;
  created?: boolean;
}
