/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { EmptyTime } from './emptyTime';
import type { RecommendationItem } from './recommendationItem';

export interface RecommendationListResponse {
  date?: string;
  condition_tag?: string;
  empty_time?: EmptyTime;
  recommendations?: RecommendationItem[];
}
