/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface RecommendationAcceptRequest {
  keep_queue_card?: boolean;
  recovery_mean?: string;
}
