/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface RecommendationItem {
  recommend_id?: number;
  title?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  deadline?: string;
  condition_tag?: string;
  source_type?: string;
  match_tier?: string;
  display_order?: number;
  recovery_means?: string[];
}
