/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

/**
 * 반복 빈도 (필수)
 */
export type RecurrenceRequestFreq =
  (typeof RecurrenceRequestFreq)[keyof typeof RecurrenceRequestFreq];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurrenceRequestFreq = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
