/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { RecurrenceRequestFreq } from './recurrenceRequestFreq';

export interface RecurrenceRequest {
  freq: RecurrenceRequestFreq;
  interval: number;
  byDay?: string;
  byMonthDay?: string;
  until: string;
}
