/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type RecurrenceFreq = (typeof RecurrenceFreq)[keyof typeof RecurrenceFreq];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurrenceFreq = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
