/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { RecurrenceRequestFreq } from './recurrenceRequestFreq';

/**
 * 반복 설정. 생략 시 반복 없는 단일 일정.
- DAILY/YEARLY: freq, interval 만 사용 (by_day·by_month_day 무시)
- WEEKLY: freq, interval (+선택 by_day)
- MONTHLY: freq, interval + by_day '또는' by_month_day 중 하나 (둘 다 주면 by_day 우선, 둘 다 생략 시 원본 일자 기준)
- until/count 는 모든 빈도에서 선택
 */
export interface RecurrenceRequest {
  /** 반복 빈도 (필수) */
  freq: RecurrenceRequestFreq;
  /** 반복 간격 'N마다' (필수, 1 이상). 1=매번, 2=한 칸 건너뛰기 */
  interval: number;
  /** [WEEKLY] 반복 요일, 복수 가능: 'MON,WED,FRI' (생략 시 원본 날짜의 요일).
[MONTHLY] 'N번째 요일'을 출현 횟수로 지정: '2WED'(2번째 수요일) / 'MON,WED'(복수 가능).
숫자 없이 'TUE'만 주면 원본 날짜 기준으로 N번째를 자동 계산.
N번째가 없는 달은 마지막 출현 요일로 폴백.
토큰: SUN/MON/TUE/WED/THU/FRI/SAT. [DAILY/YEARLY 에서는 무시] */
  by_day?: string;
  /** [MONTHLY 전용] 매월 반복할 일자, 복수 가능: '16' 또는 '1,17'.
해당 일자가 없는 달(예: 2월 31일)은 그 달 말일로 당김. 1~31 범위 밖 값은 무시.
(by_day 가 함께 오면 무시됨) */
  by_month_day?: string;
  /** 종료일 (inclusive, 그날 포함). 종료 안 함이면 null */
  until?: string;
  /** 총 발생 횟수 (원본 포함). 예: 3 → 원본 + 2회. 무제한이면 null. until 과 함께 주면 더 빨리 끝나는 쪽 적용 */
  count?: number;
}
