/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { RecurrenceFreq } from './recurrenceFreq';

export interface Recurrence {
  freq?: RecurrenceFreq;
  interval?: number;
  by_day?: string;
  by_month_day?: string;
  until?: string;
  count?: number;
}
