/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleUpdateRequestConditionTag } from './scheduleUpdateRequestConditionTag';
import type { ScheduleUpdateRequestStatus } from './scheduleUpdateRequestStatus';
import type { ScheduleUpdateRequestRemindType } from './scheduleUpdateRequestRemindType';
import type { ScheduleUpdateRequestRemindSoundType } from './scheduleUpdateRequestRemindSoundType';

export interface ScheduleUpdateRequest {
  title?: string;
  condition_tag?: ScheduleUpdateRequestConditionTag;
  /**
   * 개인 태그 이름 목록 (일정당 최대 10개, 각 1~25자). 전달하면 일정의 태그 전체가 이 목록으로 교체됨 — 미전송(null)이면 기존 유지, 빈 배열이면 전체 해제
   * @minItems 0
   * @maxItems 10
   */
  personal_tags?: string[];
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  memo?: string;
  /**
   * 대표 위치(장소명/주소 등, 최대 200자). 전달하면 갱신, 미전송(null)이면 기존 유지
   * @minLength 0
   * @maxLength 200
   */
  location?: string;
  /**
   * 상세 위치(대표 위치 내 세부, 최대 200자). 전달하면 갱신, 미전송(null)이면 기존 유지
   * @minLength 0
   * @maxLength 200
   */
  location_detail?: string;
  status?: ScheduleUpdateRequestStatus;
  is_remind_on?: boolean;
  remind_minutes?: number;
  remind_type?: ScheduleUpdateRequestRemindType;
  remind_sound_type?: ScheduleUpdateRequestRemindSoundType;
}
