/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { DailyCount } from './dailyCount';

export interface ScheduleMonthlyResponse {
  year_month?: string;
  schedules?: DailyCount[];
}
