/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleUpdateRequestConditionTag } from './scheduleUpdateRequestConditionTag';
import type { ScheduleUpdateRequestStatus } from './scheduleUpdateRequestStatus';
import type { ScheduleUpdateRequestRemindType } from './scheduleUpdateRequestRemindType';
import type { ScheduleUpdateRequestRemindSoundType } from './scheduleUpdateRequestRemindSoundType';

export interface ScheduleUpdateRequest {
  title?: string;
  condition_tag?: ScheduleUpdateRequestConditionTag;
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  memo?: string;
  status?: ScheduleUpdateRequestStatus;
  is_remind_on?: boolean;
  remind_minutes?: number;
  remind_type?: ScheduleUpdateRequestRemindType;
  remind_sound_type?: ScheduleUpdateRequestRemindSoundType;
}
