/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleCreateRequestConditionTag } from './scheduleCreateRequestConditionTag';
import type { ScheduleCreateRequestRemindType } from './scheduleCreateRequestRemindType';
import type { ScheduleCreateRequestRemindSoundType } from './scheduleCreateRequestRemindSoundType';
import type { RecurrenceRequest } from './recurrenceRequest';

export interface ScheduleCreateRequest {
  /** @minLength 1 */
  title: string;
  condition_tag: ScheduleCreateRequestConditionTag;
  /**
   * 개인 태그 이름 목록 (선택, 일정당 최대 10개, 각 1~25자). 같은 이름은 대소문자 무시하고 재사용됨
   * @minItems 0
   * @maxItems 10
   */
  personal_tags?: string[];
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  /**
   * 대표 위치(장소명/주소 등, 선택, 최대 200자). 좌표(latitude/longitude)와 독립적으로 저장됨
   * @minLength 0
   * @maxLength 200
   */
  location?: string;
  /**
   * 상세 위치(대표 위치 내 세부, 선택, 최대 200자)
   * @minLength 0
   * @maxLength 200
   */
  location_detail?: string;
  latitude?: number;
  longitude?: number;
  memo?: string;
  is_remind_on: boolean;
  remind_minutes?: number;
  remind_type?: ScheduleCreateRequestRemindType;
  remind_sound_type?: ScheduleCreateRequestRemindSoundType;
  recurrence?: RecurrenceRequest;
}
