/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type ScheduleDetailResponseStatus =
  (typeof ScheduleDetailResponseStatus)[keyof typeof ScheduleDetailResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleDetailResponseStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
} as const;
