/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleDetailResponseStatus } from './scheduleDetailResponseStatus';
import type { ScheduleDetailResponseConditionTag } from './scheduleDetailResponseConditionTag';
import type { ScheduleDetailResponseRemindType } from './scheduleDetailResponseRemindType';
import type { ScheduleDetailResponseRemindSoundType } from './scheduleDetailResponseRemindSoundType';

export interface ScheduleDetailResponse {
  scheduleId?: number;
  title?: string;
  date?: string;
  startTime?: string;
  endTime?: string;
  estimatedTime?: number;
  isQueue?: boolean;
  status?: ScheduleDetailResponseStatus;
  conditionTag?: ScheduleDetailResponseConditionTag;
  memo?: string;
  location?: string;
  isRemindOn?: boolean;
  remindMinutes?: number;
  remindType?: ScheduleDetailResponseRemindType;
  remindSoundType?: ScheduleDetailResponseRemindSoundType;
  isRecurring?: boolean;
  isConflict?: boolean;
  latitude?: number;
  longitude?: number;
}
