/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type ScheduleDetailResponseRemindSoundType =
  (typeof ScheduleDetailResponseRemindSoundType)[keyof typeof ScheduleDetailResponseRemindSoundType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleDetailResponseRemindSoundType = {
  SOUND: 'SOUND',
  VIBRATE: 'VIBRATE',
} as const;
