/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleUpdateRequestConditionTag } from './scheduleUpdateRequestConditionTag';
import type { LocalTime } from './localTime';
import type { ScheduleUpdateRequestStatus } from './scheduleUpdateRequestStatus';
import type { ScheduleUpdateRequestRemindType } from './scheduleUpdateRequestRemindType';
import type { ScheduleUpdateRequestRemindSoundType } from './scheduleUpdateRequestRemindSoundType';

export interface ScheduleUpdateRequest {
  title?: string;
  conditionTag?: ScheduleUpdateRequestConditionTag;
  date?: string;
  startTime?: LocalTime;
  endTime?: LocalTime;
  estimatedTime?: number;
  memo?: string;
  status?: ScheduleUpdateRequestStatus;
  isRemindOn?: boolean;
  remindMinutes?: number;
  remindType?: ScheduleUpdateRequestRemindType;
  remindSoundType?: ScheduleUpdateRequestRemindSoundType;
}
