/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleGetResponseStatus } from './scheduleGetResponseStatus';
import type { ScheduleGetResponseConditionTag } from './scheduleGetResponseConditionTag';

export interface ScheduleGetResponse {
  schedule_id?: number;
  title?: string;
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  is_queue?: boolean;
  status?: ScheduleGetResponseStatus;
  condition_tag?: ScheduleGetResponseConditionTag;
  personal_tags?: string[];
}
