/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleCreateRequestConditionTag } from './scheduleCreateRequestConditionTag';
import type { LocalTime } from './localTime';
import type { ScheduleCreateRequestRemindType } from './scheduleCreateRequestRemindType';
import type { ScheduleCreateRequestRemindSoundType } from './scheduleCreateRequestRemindSoundType';
import type { RecurrenceRequest } from './recurrenceRequest';

export interface ScheduleCreateRequest {
  title: string;
  conditionTag: ScheduleCreateRequestConditionTag;
  personalTags?: string[];
  date?: string;
  startTime?: LocalTime;
  endTime?: LocalTime;
  estimatedTime?: number;
  latitude?: number;
  longitude?: number;
  memo?: string;
  isRemindOn: boolean;
  remindMinutes?: number;
  remindType?: ScheduleCreateRequestRemindType;
  remindSoundType?: ScheduleCreateRequestRemindSoundType;
  recurrence?: RecurrenceRequest;
}
