/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleDetailResponseStatus } from './scheduleDetailResponseStatus';
import type { ScheduleDetailResponseConditionTag } from './scheduleDetailResponseConditionTag';
import type { ScheduleDetailResponseRemindType } from './scheduleDetailResponseRemindType';
import type { ScheduleDetailResponseRemindSoundType } from './scheduleDetailResponseRemindSoundType';

export interface ScheduleDetailResponse {
  schedule_id?: number;
  title?: string;
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  is_queue?: boolean;
  status?: ScheduleDetailResponseStatus;
  condition_tag?: ScheduleDetailResponseConditionTag;
  memo?: string;
  location?: string;
  is_remind_on?: boolean;
  remind_minutes?: number;
  remind_type?: ScheduleDetailResponseRemindType;
  remind_sound_type?: ScheduleDetailResponseRemindSoundType;
  is_recurring?: boolean;
  is_conflict?: boolean;
  latitude?: number;
  longitude?: number;
}
