/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type ScheduleCreateRequestRemindType =
  (typeof ScheduleCreateRequestRemindType)[keyof typeof ScheduleCreateRequestRemindType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleCreateRequestRemindType = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
} as const;
