/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type ScheduleUpdateRequestRemindType =
  (typeof ScheduleUpdateRequestRemindType)[keyof typeof ScheduleUpdateRequestRemindType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleUpdateRequestRemindType = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
} as const;
