/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface ScheduleCreateResponse {
  schedule_id?: number;
  title?: string;
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  is_queue?: boolean;
  personal_tags?: string[];
}
