/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type ScheduleDetailResponseRemindType =
  (typeof ScheduleDetailResponseRemindType)[keyof typeof ScheduleDetailResponseRemindType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduleDetailResponseRemindType = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
} as const;
