/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface ScheduleCreateResponse {
  scheduleId?: number;
  title?: string;
  date?: string;
  startTime?: string;
  endTime?: string;
  estimatedTime?: number;
  isQueue?: boolean;
}
