/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface ScheduleSearchResponse {
  schedule_id?: number;
  title?: string;
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  condition_tag?: string;
  personal_tags?: string[];
  status?: string;
  is_recommended?: boolean;
  is_conflict?: boolean;
}
