/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { ScheduleCreateRequestConditionTag } from './scheduleCreateRequestConditionTag';
import type { ScheduleCreateRequestRemindType } from './scheduleCreateRequestRemindType';
import type { ScheduleCreateRequestRemindSoundType } from './scheduleCreateRequestRemindSoundType';
import type { RecurrenceRequest } from './recurrenceRequest';

export interface ScheduleCreateRequest {
  /** @minLength 1 */
  title: string;
  condition_tag: ScheduleCreateRequestConditionTag;
  personal_tags?: string[];
  date?: string;
  start_time?: string;
  end_time?: string;
  estimated_time?: number;
  latitude?: number;
  longitude?: number;
  memo?: string;
  is_remind_on: boolean;
  remind_minutes?: number;
  remind_type?: ScheduleCreateRequestRemindType;
  remind_sound_type?: ScheduleCreateRequestRemindSoundType;
  recurrence?: RecurrenceRequest;
}
