/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type SearchSchedulesConditionTagsItem =
  (typeof SearchSchedulesConditionTagsItem)[keyof typeof SearchSchedulesConditionTagsItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchSchedulesConditionTagsItem = {
  CORE_TASK: 'CORE_TASK',
  BRAIN_WORK: 'BRAIN_WORK',
  SIMPLE_TASK: 'SIMPLE_TASK',
  DAILY_TASK: 'DAILY_TASK',
  URGENT: 'URGENT',
  RECOVERY: 'RECOVERY',
} as const;
