/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { SearchSchedulesStatusItem } from './searchSchedulesStatusItem';
import type { SearchSchedulesConditionTagsItem } from './searchSchedulesConditionTagsItem';

export type SearchSchedulesParams = {
  /**
   * 제목 검색 키워드
   */
  keyword?: string;
  /**
   * true=큐 카드, false=핀 카드
   */
  isQueue?: boolean;
  /**
   * 진행 상태(TODO/IN_PROGRESS/DONE), 복수 가능
   */
  status?: SearchSchedulesStatusItem[];
  /**
   * 컨디션 태그, 복수 가능
   */
  conditionTags?: SearchSchedulesConditionTagsItem[];
  /**
   * 개인 태그 이름, 복수 가능
   */
  personalTags?: string[];
  /**
   * 기간 필터 시작 일시(ISO, 예: 2026-06-28T14:30). 겹치는 핀 카드만(큐 카드 제외)
   */
  startDate?: string;
  /**
   * 기간 필터 종료 일시(ISO, 예: 2026-07-01T18:00)
   */
  endDate?: string;
  /**
   * 페이지 번호(0부터, 기본 0)
   */
  page?: number;
};
