/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface SleepRecord {
  sleep_id?: number;
  duration_minutes?: number;
  bed_time?: string;
  wake_up_time?: string;
  isNap?: boolean;
  isAllNight?: boolean;
  created_at?: string;
}
