/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface SleepCreate {
  /** 취침 시각 */
  bed_time: string;
  /** 기상 시각 */
  wake_up_time: string;
  /** 낮잠 여부 */
  is_nap: boolean;
  /** 밤샘 여부 */
  is_all_night: boolean;
}
