/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface SleepResponse {
  sleepId?: number;
  durationMinutes?: number;
  totalDurationMinutes?: number;
  bedTime?: string;
  wakeUpTime?: string;
  originalBedTime?: string;
  originalWakeUpTime?: string;
  isNap?: boolean;
  isAllNight?: boolean;
  isContinuousSleep?: boolean;
  continuousSleepGroupId?: string;
  createdAt?: string;
  /** 개별 수면 기록 상태 문구 */
  sleepRecordComment?: string;
}
