/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface SleepRecord {
  sleep_id?: number;
  duration_minutes?: number;
  total_duration_minutes?: number;
  bed_time?: string;
  wake_up_time?: string;
  original_bed_time?: string;
  original_wake_up_time?: string;
  isNap?: boolean;
  isAllNight?: boolean;
  isContinuousSleep?: boolean;
  continuous_sleep_group_id?: string;
  created_at?: string;
  /** 개별 수면 기록 상태 문구 */
  sleep_record_comment?: string;
}
