/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface SocialLoginResponseDto {
  /** @minLength 1 */
  access_token: string;
  /** @minLength 1 */
  refresh_token: string;
  is_new_user: boolean;
  onboarding_completed: boolean;
}
