/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface TagRecommendationRequestDto {
  /**
   * @minLength 0
   * @maxLength 50
   */
  title: string;
}
