/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export type TransportRequestTransportTypesItem =
  (typeof TransportRequestTransportTypesItem)[keyof typeof TransportRequestTransportTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransportRequestTransportTypesItem = {
  WALK: 'WALK',
  BICYCLE: 'BICYCLE',
  PUBLIC_TRANSPORT: 'PUBLIC_TRANSPORT',
  CAR: 'CAR',
} as const;
