/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import type { TransportResponseTransportTypesItem } from './transportResponseTransportTypesItem';

export interface TransportResponse {
  member_id?: number;
  transport_types?: TransportResponseTransportTypesItem[];
}
