/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface UpdateConditions {
  target_duration: number;
  danger_threshold: number;
  lack_threshold: number;
  optimal_threshold: number;
}
