/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */

export interface UpdateConditions {
  targetDuration: number;
  dangerThreshold: number;
  lackThreshold: number;
  optimalThreshold: number;
}
