/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetSchedulesByDateParams,
  GetSchedulesByMonthParams,
  GetSchedulesByWeekParams,
  PersonalTagResponse,
  ScheduleCreateRequest,
  ScheduleCreateResponse,
  ScheduleDetailResponse,
  ScheduleGetResponse,
  ScheduleMonthlyResponse,
  ScheduleUpdateRequest,
  ScheduleWeeklyResponse,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 특정 날짜의 일정 목록을 조회합니다.
 * @summary 일정 일별 조회
 */
export const getSchedulesByDate = (
  params: GetSchedulesByDateParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleGetResponse[]>(
    { url: `/schedule`, method: 'GET', params, signal },
    options,
  );
};

export const getGetSchedulesByDateQueryKey = (params?: GetSchedulesByDateParams) => {
  return [`/schedule`, ...(params ? [params] : [])] as const;
};

export const getGetSchedulesByDateQueryOptions = <
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSchedulesByDateQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulesByDate>>> = ({ signal }) =>
    getSchedulesByDate(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSchedulesByDate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSchedulesByDateQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSchedulesByDate>>
>;
export type GetSchedulesByDateQueryError = ErrorType<unknown>;

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 일정 일별 조회
 */

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSchedulesByDateQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 새로운 일정을 생성합니다. 시작/종료 시간이 없으면 큐카드로 등록됩니다.
 * @summary 일정 생성
 */
export const createSchedule = (
  scheduleCreateRequest: BodyType<ScheduleCreateRequest>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleCreateResponse>(
    {
      url: `/schedule`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: scheduleCreateRequest,
      signal,
    },
    options,
  );
};

export const getCreateScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSchedule>>,
    TError,
    { data: BodyType<ScheduleCreateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSchedule>>,
  TError,
  { data: BodyType<ScheduleCreateRequest> },
  TContext
> => {
  const mutationKey = ['createSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSchedule>>,
    { data: BodyType<ScheduleCreateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createSchedule(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof createSchedule>>>;
export type CreateScheduleMutationBody = BodyType<ScheduleCreateRequest>;
export type CreateScheduleMutationError = ErrorType<unknown>;

/**
 * @summary 일정 생성
 */
export const useCreateSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSchedule>>,
      TError,
      { data: BodyType<ScheduleCreateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSchedule>>,
  TError,
  { data: BodyType<ScheduleCreateRequest> },
  TContext
> => {
  const mutationOptions = getCreateScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 특정 일정의 상세 정보를 조회합니다.
 * @summary 일정 상세 조회
 */
export const getScheduleDetail = (
  scheduleId: number,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleDetailResponse>(
    { url: `/schedule/${scheduleId}`, method: 'GET', signal },
    options,
  );
};

export const getGetScheduleDetailQueryKey = (scheduleId?: number) => {
  return [`/schedule/${scheduleId}`] as const;
};

export const getGetScheduleDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetScheduleDetailQueryKey(scheduleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getScheduleDetail>>> = ({ signal }) =>
    getScheduleDetail(scheduleId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!scheduleId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getScheduleDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetScheduleDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getScheduleDetail>>
>;
export type GetScheduleDetailQueryError = ErrorType<unknown>;

export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleDetail>>,
          TError,
          Awaited<ReturnType<typeof getScheduleDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleDetail>>,
          TError,
          Awaited<ReturnType<typeof getScheduleDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 일정 상세 조회
 */

export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetScheduleDetailQueryOptions(scheduleId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 특정 일정을 삭제합니다.
 * @summary 일정 삭제
 */
export const deleteSchedule = (
  scheduleId: number,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<void>({ url: `/schedule/${scheduleId}`, method: 'DELETE' }, options);
};

export const getDeleteScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSchedule>>,
    TError,
    { scheduleId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { scheduleId: number },
  TContext
> => {
  const mutationKey = ['deleteSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSchedule>>,
    { scheduleId: number }
  > = (props) => {
    const { scheduleId } = props ?? {};

    return deleteSchedule(scheduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSchedule>>>;

export type DeleteScheduleMutationError = ErrorType<unknown>;

/**
 * @summary 일정 삭제
 */
export const useDeleteSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSchedule>>,
      TError,
      { scheduleId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { scheduleId: number },
  TContext
> => {
  const mutationOptions = getDeleteScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 특정 일정의 정보를 수정합니다. 전달한 필드만 업데이트됩니다. personalTags를 전달하면 태그 전체가 해당 목록으로 교체됩니다.
 * @summary 일정 수정
 */
export const updateSchedule = (
  scheduleId: number,
  scheduleUpdateRequest: BodyType<ScheduleUpdateRequest>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ScheduleDetailResponse>(
    {
      url: `/schedule/${scheduleId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: scheduleUpdateRequest,
    },
    options,
  );
};

export const getUpdateScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSchedule>>,
    TError,
    { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSchedule>>,
  TError,
  { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
  TContext
> => {
  const mutationKey = ['updateSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSchedule>>,
    { scheduleId: number; data: BodyType<ScheduleUpdateRequest> }
  > = (props) => {
    const { scheduleId, data } = props ?? {};

    return updateSchedule(scheduleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof updateSchedule>>>;
export type UpdateScheduleMutationBody = BodyType<ScheduleUpdateRequest>;
export type UpdateScheduleMutationError = ErrorType<unknown>;

/**
 * @summary 일정 수정
 */
export const useUpdateSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSchedule>>,
      TError,
      { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSchedule>>,
  TError,
  { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
  TContext
> => {
  const mutationOptions = getUpdateScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 날짜가 포함된 주(일~토)의 일정 목록을 조회합니다.
 * @summary 일정 주별 조회
 */
export const getSchedulesByWeek = (
  params: GetSchedulesByWeekParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleWeeklyResponse>(
    { url: `/schedule/weekly`, method: 'GET', params, signal },
    options,
  );
};

export const getGetSchedulesByWeekQueryKey = (params?: GetSchedulesByWeekParams) => {
  return [`/schedule/weekly`, ...(params ? [params] : [])] as const;
};

export const getGetSchedulesByWeekQueryOptions = <
  TData = Awaited<ReturnType<typeof getSchedulesByWeek>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByWeekParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByWeek>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSchedulesByWeekQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulesByWeek>>> = ({ signal }) =>
    getSchedulesByWeek(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSchedulesByWeek>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSchedulesByWeekQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSchedulesByWeek>>
>;
export type GetSchedulesByWeekQueryError = ErrorType<unknown>;

export function useGetSchedulesByWeek<
  TData = Awaited<ReturnType<typeof getSchedulesByWeek>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByWeekParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByWeek>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByWeek>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByWeek>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByWeek<
  TData = Awaited<ReturnType<typeof getSchedulesByWeek>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByWeekParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByWeek>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByWeek>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByWeek>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByWeek<
  TData = Awaited<ReturnType<typeof getSchedulesByWeek>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByWeekParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByWeek>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 일정 주별 조회
 */

export function useGetSchedulesByWeek<
  TData = Awaited<ReturnType<typeof getSchedulesByWeek>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByWeekParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByWeek>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSchedulesByWeekQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 로그인한 멤버가 등록한 개인 태그 전체를 조회합니다. (태그 검색/재사용 화면용)
 * @summary 개인 태그 목록 조회
 */
export const getPersonalTags = (
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<PersonalTagResponse[]>(
    { url: `/schedule/tags`, method: 'GET', signal },
    options,
  );
};

export const getGetPersonalTagsQueryKey = () => {
  return [`/schedule/tags`] as const;
};

export const getGetPersonalTagsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonalTags>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalTags>>, TError, TData>>;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPersonalTagsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPersonalTags>>> = ({ signal }) =>
    getPersonalTags(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonalTags>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPersonalTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getPersonalTags>>>;
export type GetPersonalTagsQueryError = ErrorType<unknown>;

export function useGetPersonalTags<
  TData = Awaited<ReturnType<typeof getPersonalTags>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalTags>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalTags>>,
          TError,
          Awaited<ReturnType<typeof getPersonalTags>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalTags<
  TData = Awaited<ReturnType<typeof getPersonalTags>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalTags>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalTags>>,
          TError,
          Awaited<ReturnType<typeof getPersonalTags>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPersonalTags<
  TData = Awaited<ReturnType<typeof getPersonalTags>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalTags>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 개인 태그 목록 조회
 */

export function useGetPersonalTags<
  TData = Awaited<ReturnType<typeof getPersonalTags>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPersonalTags>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPersonalTagsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 해당 월의 캘린더 뷰 기준(첫째 주 일요일 ~ 마지막 주 토요일) 날짜별 일정 개수를 조회합니다.
 * @summary 일정 월별 조회
 */
export const getSchedulesByMonth = (
  params: GetSchedulesByMonthParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleMonthlyResponse>(
    { url: `/schedule/monthly`, method: 'GET', params, signal },
    options,
  );
};

export const getGetSchedulesByMonthQueryKey = (params?: GetSchedulesByMonthParams) => {
  return [`/schedule/monthly`, ...(params ? [params] : [])] as const;
};

export const getGetSchedulesByMonthQueryOptions = <
  TData = Awaited<ReturnType<typeof getSchedulesByMonth>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByMonthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByMonth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSchedulesByMonthQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulesByMonth>>> = ({ signal }) =>
    getSchedulesByMonth(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSchedulesByMonth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSchedulesByMonthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSchedulesByMonth>>
>;
export type GetSchedulesByMonthQueryError = ErrorType<unknown>;

export function useGetSchedulesByMonth<
  TData = Awaited<ReturnType<typeof getSchedulesByMonth>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByMonthParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByMonth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByMonth>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByMonth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByMonth<
  TData = Awaited<ReturnType<typeof getSchedulesByMonth>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByMonthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByMonth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByMonth>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByMonth>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByMonth<
  TData = Awaited<ReturnType<typeof getSchedulesByMonth>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByMonthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByMonth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 일정 월별 조회
 */

export function useGetSchedulesByMonth<
  TData = Awaited<ReturnType<typeof getSchedulesByMonth>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByMonthParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByMonth>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSchedulesByMonthQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
