/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetSchedulesByDateParams,
  ScheduleCreateRequest,
  ScheduleCreateResponse,
  ScheduleDetailResponse,
  ScheduleGetResponse,
  ScheduleUpdateRequest,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getSchedulesByDate = (
  params: GetSchedulesByDateParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleGetResponse[]>(
    { url: `/api/schedule`, method: 'GET', params, signal },
    options,
  );
};

export const getGetSchedulesByDateQueryKey = (params?: GetSchedulesByDateParams) => {
  return [`/api/schedule`, ...(params ? [params] : [])] as const;
};

export const getGetSchedulesByDateQueryOptions = <
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSchedulesByDateQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulesByDate>>> = ({ signal }) =>
    getSchedulesByDate(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSchedulesByDate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSchedulesByDateQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSchedulesByDate>>
>;
export type GetSchedulesByDateQueryError = ErrorType<unknown>;

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = ErrorType<unknown>,
>(
  params: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSchedulesByDateQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createSchedule = (
  scheduleCreateRequest: BodyType<ScheduleCreateRequest>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleCreateResponse>(
    {
      url: `/api/schedule`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: scheduleCreateRequest,
      signal,
    },
    options,
  );
};

export const getCreateScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSchedule>>,
    TError,
    { data: BodyType<ScheduleCreateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSchedule>>,
  TError,
  { data: BodyType<ScheduleCreateRequest> },
  TContext
> => {
  const mutationKey = ['createSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSchedule>>,
    { data: BodyType<ScheduleCreateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createSchedule(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof createSchedule>>>;
export type CreateScheduleMutationBody = BodyType<ScheduleCreateRequest>;
export type CreateScheduleMutationError = ErrorType<unknown>;

export const useCreateSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSchedule>>,
      TError,
      { data: BodyType<ScheduleCreateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSchedule>>,
  TError,
  { data: BodyType<ScheduleCreateRequest> },
  TContext
> => {
  const mutationOptions = getCreateScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getScheduleDetail = (
  scheduleId: number,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ScheduleDetailResponse>(
    { url: `/api/schedule/${scheduleId}`, method: 'GET', signal },
    options,
  );
};

export const getGetScheduleDetailQueryKey = (scheduleId?: number) => {
  return [`/api/schedule/${scheduleId}`] as const;
};

export const getGetScheduleDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetScheduleDetailQueryKey(scheduleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getScheduleDetail>>> = ({ signal }) =>
    getScheduleDetail(scheduleId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!scheduleId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getScheduleDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetScheduleDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getScheduleDetail>>
>;
export type GetScheduleDetailQueryError = ErrorType<unknown>;

export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleDetail>>,
          TError,
          Awaited<ReturnType<typeof getScheduleDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleDetail>>,
          TError,
          Awaited<ReturnType<typeof getScheduleDetail>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetScheduleDetail<
  TData = Awaited<ReturnType<typeof getScheduleDetail>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleDetail>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetScheduleDetailQueryOptions(scheduleId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteSchedule = (
  scheduleId: number,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<void>({ url: `/api/schedule/${scheduleId}`, method: 'DELETE' }, options);
};

export const getDeleteScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSchedule>>,
    TError,
    { scheduleId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { scheduleId: number },
  TContext
> => {
  const mutationKey = ['deleteSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSchedule>>,
    { scheduleId: number }
  > = (props) => {
    const { scheduleId } = props ?? {};

    return deleteSchedule(scheduleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSchedule>>>;

export type DeleteScheduleMutationError = ErrorType<unknown>;

export const useDeleteSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSchedule>>,
      TError,
      { scheduleId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { scheduleId: number },
  TContext
> => {
  const mutationOptions = getDeleteScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateSchedule = (
  scheduleId: number,
  scheduleUpdateRequest: BodyType<ScheduleUpdateRequest>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ScheduleDetailResponse>(
    {
      url: `/api/schedule/${scheduleId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: scheduleUpdateRequest,
    },
    options,
  );
};

export const getUpdateScheduleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSchedule>>,
    TError,
    { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSchedule>>,
  TError,
  { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
  TContext
> => {
  const mutationKey = ['updateSchedule'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSchedule>>,
    { scheduleId: number; data: BodyType<ScheduleUpdateRequest> }
  > = (props) => {
    const { scheduleId, data } = props ?? {};

    return updateSchedule(scheduleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof updateSchedule>>>;
export type UpdateScheduleMutationBody = BodyType<ScheduleUpdateRequest>;
export type UpdateScheduleMutationError = ErrorType<unknown>;

export const useUpdateSchedule = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSchedule>>,
      TError,
      { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSchedule>>,
  TError,
  { scheduleId: number; data: BodyType<ScheduleUpdateRequest> },
  TContext
> => {
  const mutationOptions = getUpdateScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
