/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseSleepResponse,
  ApiResponseVoid,
  SleepCreate,
  SleepUpdate,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 사용자가 기록한 밤잠 또는 낮잠 세션 정보를 등록합니다.<br>
사용자는 취침 시각, 기상 시각, 낮잠 여부, 밤샘 여부를 입력합니다.<br><br>

- durationMinutes는 요청값으로 받지 않습니다.<br>
- 서버에서 wakeUpTime - bedTime 값으로 durationMinutes를 계산합니다.<br>
- isAllNight가 true이면 durationMinutes는 0으로 저장합니다.<br>
- isNap과 isAllNight는 동시에 true일 수 없습니다.<br>
- created_at은 서버에서 자동 생성됩니다.

 * @summary 수면 입력
 */
export const createSleep = (
  sleepCreate: BodyType<SleepCreate>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseSleepResponse>(
    {
      url: `/sleeps`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sleepCreate,
      signal,
    },
    options,
  );
};

export const getCreateSleepMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSleep>>,
    TError,
    { data: BodyType<SleepCreate> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSleep>>,
  TError,
  { data: BodyType<SleepCreate> },
  TContext
> => {
  const mutationKey = ['createSleep'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSleep>>,
    { data: BodyType<SleepCreate> }
  > = (props) => {
    const { data } = props ?? {};

    return createSleep(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSleepMutationResult = NonNullable<Awaited<ReturnType<typeof createSleep>>>;
export type CreateSleepMutationBody = BodyType<SleepCreate>;
export type CreateSleepMutationError = ErrorType<unknown>;

/**
 * @summary 수면 입력
 */
export const useCreateSleep = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSleep>>,
      TError,
      { data: BodyType<SleepCreate> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSleep>>,
  TError,
  { data: BodyType<SleepCreate> },
  TContext
> => {
  const mutationOptions = getCreateSleepMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 인증된 사용자의 수면 기록을 조회합니다.<br>
본인의 수면 기록만 조회할 수 있습니다.<br><br>

- durationMinutes는 서버가 bedTime과 wakeUpTime 기준으로 계산한 값입니다.<br>
- isNap이 true이면 낮잠, false이면 밤잠 기록입니다.<br>
- isAllNight가 true이면 밤샘 기록이며 durationMinutes는 0입니다.

 * @summary 수면 조회
 */
export const getSleep = (
  sleepId: number,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseSleepResponse>(
    { url: `/sleeps/${sleepId}`, method: 'GET', signal },
    options,
  );
};

export const getGetSleepQueryKey = (sleepId?: number) => {
  return [`/sleeps/${sleepId}`] as const;
};

export const getGetSleepQueryOptions = <
  TData = Awaited<ReturnType<typeof getSleep>>,
  TError = ErrorType<unknown>,
>(
  sleepId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleep>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSleepQueryKey(sleepId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSleep>>> = ({ signal }) =>
    getSleep(sleepId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!sleepId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSleep>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSleepQueryResult = NonNullable<Awaited<ReturnType<typeof getSleep>>>;
export type GetSleepQueryError = ErrorType<unknown>;

export function useGetSleep<
  TData = Awaited<ReturnType<typeof getSleep>>,
  TError = ErrorType<unknown>,
>(
  sleepId: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleep>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSleep>>,
          TError,
          Awaited<ReturnType<typeof getSleep>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSleep<
  TData = Awaited<ReturnType<typeof getSleep>>,
  TError = ErrorType<unknown>,
>(
  sleepId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleep>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSleep>>,
          TError,
          Awaited<ReturnType<typeof getSleep>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSleep<
  TData = Awaited<ReturnType<typeof getSleep>>,
  TError = ErrorType<unknown>,
>(
  sleepId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleep>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 수면 조회
 */

export function useGetSleep<
  TData = Awaited<ReturnType<typeof getSleep>>,
  TError = ErrorType<unknown>,
>(
  sleepId: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleep>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSleepQueryOptions(sleepId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 기존에 입력한 밤잠 또는 낮잠 수면 세션을 삭제합니다.<br>
삭제 대상은 sleepId로 구분합니다.<br><br>

- 삭제 후 해당 날짜의 수면 부족 패널티 및 종합 컨디션 점수 재계산 수정 예정

 * @summary 수면 삭제
 */
export const deleteSleep = (sleepId: number, options?: SecondParameter<typeof apiMutator>) => {
  return apiMutator<ApiResponseVoid>({ url: `/sleeps/${sleepId}`, method: 'DELETE' }, options);
};

export const getDeleteSleepMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSleep>>,
    TError,
    { sleepId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSleep>>,
  TError,
  { sleepId: number },
  TContext
> => {
  const mutationKey = ['deleteSleep'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSleep>>,
    { sleepId: number }
  > = (props) => {
    const { sleepId } = props ?? {};

    return deleteSleep(sleepId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSleepMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSleep>>>;

export type DeleteSleepMutationError = ErrorType<unknown>;

/**
 * @summary 수면 삭제
 */
export const useDeleteSleep = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSleep>>,
      TError,
      { sleepId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSleep>>,
  TError,
  { sleepId: number },
  TContext
> => {
  const mutationOptions = getDeleteSleepMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 기존에 입력한 밤잠 또는 낮잠 수면 세션 정보를 수정합니다.<br>
사용자는 취침 시각, 기상 시각, 낮잠 여부, 밤샘 여부를 입력합니다.<br><br>

- durationMinutes는 요청값으로 받지 않습니다.<br>
- 서버에서 wakeUpTime - bedTime 값으로 durationMinutes를 다시 계산합니다.<br>
- isAllNight가 true이면 durationMinutes는 0으로 저장합니다.<br>
- isNap과 isAllNight는 동시에 true일 수 없습니다.<br>
- created_at은 최초 생성 시각이므로 수정해도 변경되지 않습니다.

 * @summary 수면 수정
 */
export const updateSleep = (
  sleepId: number,
  sleepUpdate: BodyType<SleepUpdate>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseSleepResponse>(
    {
      url: `/sleeps/${sleepId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: sleepUpdate,
    },
    options,
  );
};

export const getUpdateSleepMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSleep>>,
    TError,
    { sleepId: number; data: BodyType<SleepUpdate> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSleep>>,
  TError,
  { sleepId: number; data: BodyType<SleepUpdate> },
  TContext
> => {
  const mutationKey = ['updateSleep'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSleep>>,
    { sleepId: number; data: BodyType<SleepUpdate> }
  > = (props) => {
    const { sleepId, data } = props ?? {};

    return updateSleep(sleepId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSleepMutationResult = NonNullable<Awaited<ReturnType<typeof updateSleep>>>;
export type UpdateSleepMutationBody = BodyType<SleepUpdate>;
export type UpdateSleepMutationError = ErrorType<unknown>;

/**
 * @summary 수면 수정
 */
export const useUpdateSleep = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSleep>>,
      TError,
      { sleepId: number; data: BodyType<SleepUpdate> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSleep>>,
  TError,
  { sleepId: number; data: BodyType<SleepUpdate> },
  TContext
> => {
  const mutationOptions = getUpdateSleepMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
