/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { GetAccessTokenParams, SocialLoginResponseDto } from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAccessToken = (
  params: GetAccessTokenParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<SocialLoginResponseDto>(
    { url: `/auth/accessToken`, method: 'POST', params, signal },
    options,
  );
};

export const getGetAccessTokenMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getAccessToken>>,
    TError,
    { params: GetAccessTokenParams },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getAccessToken>>,
  TError,
  { params: GetAccessTokenParams },
  TContext
> => {
  const mutationKey = ['getAccessToken'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getAccessToken>>,
    { params: GetAccessTokenParams }
  > = (props) => {
    const { params } = props ?? {};

    return getAccessToken(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof getAccessToken>>>;

export type GetAccessTokenMutationError = ErrorType<unknown>;

export const useGetAccessToken = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getAccessToken>>,
      TError,
      { params: GetAccessTokenParams },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getAccessToken>>,
  TError,
  { params: GetAccessTokenParams },
  TContext
> => {
  const mutationOptions = getGetAccessTokenMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
