/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseGetMethods,
  ApiResponseSleepConditionResponse,
  ApiResponseUpdateMethods,
  UpdateConditions,
  UpdateMethods,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 회원이 설정한 수면 시간별 컨디션 기준을 조회합니다.
 * @summary 수면 시간별 컨디션 조회
 */
export const getSleepConditions = (
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseSleepConditionResponse>(
    { url: `/member-settings/sleep-conditions`, method: 'GET', signal },
    options,
  );
};

export const getGetSleepConditionsQueryKey = () => {
  return [`/member-settings/sleep-conditions`] as const;
};

export const getGetSleepConditionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSleepConditions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleepConditions>>, TError, TData>>;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSleepConditionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSleepConditions>>> = ({ signal }) =>
    getSleepConditions(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSleepConditions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSleepConditionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSleepConditions>>
>;
export type GetSleepConditionsQueryError = ErrorType<unknown>;

export function useGetSleepConditions<
  TData = Awaited<ReturnType<typeof getSleepConditions>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleepConditions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSleepConditions>>,
          TError,
          Awaited<ReturnType<typeof getSleepConditions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSleepConditions<
  TData = Awaited<ReturnType<typeof getSleepConditions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSleepConditions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSleepConditions>>,
          TError,
          Awaited<ReturnType<typeof getSleepConditions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSleepConditions<
  TData = Awaited<ReturnType<typeof getSleepConditions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleepConditions>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 수면 시간별 컨디션 조회
 */

export function useGetSleepConditions<
  TData = Awaited<ReturnType<typeof getSleepConditions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSleepConditions>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSleepConditionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 수면 시간별 컨디션 기준을 설정합니다. 모든 값은 30분 단위이며, 과다 기준값은 720분으로 고정됩니다.
 * @summary 수면 시간별 컨디션 설정 저장 및 수정
 */
export const updateSleepConditions = (
  updateConditions: BodyType<UpdateConditions>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseSleepConditionResponse>(
    {
      url: `/member-settings/sleep-conditions`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateConditions,
    },
    options,
  );
};

export const getUpdateSleepConditionsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSleepConditions>>,
    TError,
    { data: BodyType<UpdateConditions> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSleepConditions>>,
  TError,
  { data: BodyType<UpdateConditions> },
  TContext
> => {
  const mutationKey = ['updateSleepConditions'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSleepConditions>>,
    { data: BodyType<UpdateConditions> }
  > = (props) => {
    const { data } = props ?? {};

    return updateSleepConditions(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSleepConditionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSleepConditions>>
>;
export type UpdateSleepConditionsMutationBody = BodyType<UpdateConditions>;
export type UpdateSleepConditionsMutationError = ErrorType<unknown>;

/**
 * @summary 수면 시간별 컨디션 설정 저장 및 수정
 */
export const useUpdateSleepConditions = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSleepConditions>>,
      TError,
      { data: BodyType<UpdateConditions> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSleepConditions>>,
  TError,
  { data: BodyType<UpdateConditions> },
  TContext
> => {
  const mutationOptions = getUpdateSleepConditionsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 회원이 설정한 기본 회복 방법과 직접 입력한 회복 방법을 조회합니다.
 * @summary 컨디션 회복 방법 조회
 */
export const getRecoveryMethods = (
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseGetMethods>(
    { url: `/member-settings/recovery-methods`, method: 'GET', signal },
    options,
  );
};

export const getGetRecoveryMethodsQueryKey = () => {
  return [`/member-settings/recovery-methods`] as const;
};

export const getGetRecoveryMethodsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecoveryMethods>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecoveryMethods>>, TError, TData>>;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecoveryMethodsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecoveryMethods>>> = ({ signal }) =>
    getRecoveryMethods(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecoveryMethods>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecoveryMethodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecoveryMethods>>
>;
export type GetRecoveryMethodsQueryError = ErrorType<unknown>;

export function useGetRecoveryMethods<
  TData = Awaited<ReturnType<typeof getRecoveryMethods>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecoveryMethods>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecoveryMethods>>,
          TError,
          Awaited<ReturnType<typeof getRecoveryMethods>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecoveryMethods<
  TData = Awaited<ReturnType<typeof getRecoveryMethods>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecoveryMethods>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecoveryMethods>>,
          TError,
          Awaited<ReturnType<typeof getRecoveryMethods>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecoveryMethods<
  TData = Awaited<ReturnType<typeof getRecoveryMethods>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecoveryMethods>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 컨디션 회복 방법 조회
 */

export function useGetRecoveryMethods<
  TData = Awaited<ReturnType<typeof getRecoveryMethods>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecoveryMethods>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRecoveryMethodsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 처음 온보딩 입력 시에도 사용 가능하며, 기존 설정이 있으면 요청값으로 전체 교체합니다.<br>defaultMethods에는 NAP, MUSIC, WALK, STRETCHING, FOOD 중 선택한 값을 넣어 주세요.<br>직접 입력값이 없으면 customMethods는 빈 배열 []로 보내 주세요.
 * @summary 컨디션 회복 방법 설정 저장 및 전체 수정
 */
export const updateRecoveryMethods = (
  updateMethods: BodyType<UpdateMethods>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseUpdateMethods>(
    {
      url: `/member-settings/recovery-methods`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateMethods,
    },
    options,
  );
};

export const getUpdateRecoveryMethodsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecoveryMethods>>,
    TError,
    { data: BodyType<UpdateMethods> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRecoveryMethods>>,
  TError,
  { data: BodyType<UpdateMethods> },
  TContext
> => {
  const mutationKey = ['updateRecoveryMethods'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRecoveryMethods>>,
    { data: BodyType<UpdateMethods> }
  > = (props) => {
    const { data } = props ?? {};

    return updateRecoveryMethods(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRecoveryMethodsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRecoveryMethods>>
>;
export type UpdateRecoveryMethodsMutationBody = BodyType<UpdateMethods>;
export type UpdateRecoveryMethodsMutationError = ErrorType<unknown>;

/**
 * @summary 컨디션 회복 방법 설정 저장 및 전체 수정
 */
export const useUpdateRecoveryMethods = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRecoveryMethods>>,
      TError,
      { data: BodyType<UpdateMethods> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateRecoveryMethods>>,
  TError,
  { data: BodyType<UpdateMethods> },
  TContext
> => {
  const mutationOptions = getUpdateRecoveryMethodsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
