/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { ApiResponseOnboardingResponse, OnboardingRequest } from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 회복 방법, 수면 컨디션, 하루 활동 패턴, 선호 이동 방식을 한 번에 저장합니다.
 * @summary 최초 온보딩 저장
 */
export const saveOnboarding = (
  onboardingRequest: BodyType<OnboardingRequest>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseOnboardingResponse>(
    {
      url: `/onboarding`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: onboardingRequest,
      signal,
    },
    options,
  );
};

export const getSaveOnboardingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveOnboarding>>,
    TError,
    { data: BodyType<OnboardingRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveOnboarding>>,
  TError,
  { data: BodyType<OnboardingRequest> },
  TContext
> => {
  const mutationKey = ['saveOnboarding'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveOnboarding>>,
    { data: BodyType<OnboardingRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return saveOnboarding(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveOnboardingMutationResult = NonNullable<Awaited<ReturnType<typeof saveOnboarding>>>;
export type SaveOnboardingMutationBody = BodyType<OnboardingRequest>;
export type SaveOnboardingMutationError = ErrorType<unknown>;

/**
 * @summary 최초 온보딩 저장
 */
export const useSaveOnboarding = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof saveOnboarding>>,
      TError,
      { data: BodyType<OnboardingRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof saveOnboarding>>,
  TError,
  { data: BodyType<OnboardingRequest> },
  TContext
> => {
  const mutationOptions = getSaveOnboardingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
