/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { KakaoLoginRequestDto, SocialLoginResponseDto } from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const kakaoLogin = (
  kakaoLoginRequestDto: BodyType<KakaoLoginRequestDto>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<SocialLoginResponseDto>(
    {
      url: `/auth/kakao`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: kakaoLoginRequestDto,
      signal,
    },
    options,
  );
};

export const getKakaoLoginMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kakaoLogin>>,
    TError,
    { data: BodyType<KakaoLoginRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kakaoLogin>>,
  TError,
  { data: BodyType<KakaoLoginRequestDto> },
  TContext
> => {
  const mutationKey = ['kakaoLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kakaoLogin>>,
    { data: BodyType<KakaoLoginRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return kakaoLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KakaoLoginMutationResult = NonNullable<Awaited<ReturnType<typeof kakaoLogin>>>;
export type KakaoLoginMutationBody = BodyType<KakaoLoginRequestDto>;
export type KakaoLoginMutationError = ErrorType<unknown>;

export const useKakaoLogin = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kakaoLogin>>,
      TError,
      { data: BodyType<KakaoLoginRequestDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kakaoLogin>>,
  TError,
  { data: BodyType<KakaoLoginRequestDto> },
  TContext
> => {
  const mutationOptions = getKakaoLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
