/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ApiResponseTagRecommendationResponseDto,
  TagRecommendationRequestDto,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const recommendTag = (
  tagRecommendationRequestDto: BodyType<TagRecommendationRequestDto>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseTagRecommendationResponseDto>(
    {
      url: `/schedules/tag-recommendation`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: tagRecommendationRequestDto,
      signal,
    },
    options,
  );
};

export const getRecommendTagMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recommendTag>>,
    TError,
    { data: BodyType<TagRecommendationRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recommendTag>>,
  TError,
  { data: BodyType<TagRecommendationRequestDto> },
  TContext
> => {
  const mutationKey = ['recommendTag'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recommendTag>>,
    { data: BodyType<TagRecommendationRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return recommendTag(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecommendTagMutationResult = NonNullable<Awaited<ReturnType<typeof recommendTag>>>;
export type RecommendTagMutationBody = BodyType<TagRecommendationRequestDto>;
export type RecommendTagMutationError = ErrorType<unknown>;

export const useRecommendTag = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recommendTag>>,
      TError,
      { data: BodyType<TagRecommendationRequestDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recommendTag>>,
  TError,
  { data: BodyType<TagRecommendationRequestDto> },
  TContext
> => {
  const mutationOptions = getRecommendTagMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
