/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseConditionRecommendationResponse,
  GetConditionRecommendationsParams,
  GetQueueCardRecommendations200,
  GetQueueCardRecommendationsParams,
  GetRecommendationsParams,
  RecommendationAcceptRequest,
  RecommendationAcceptResponse,
  RecommendationListResponse,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 추천을 패스(넘기기)합니다. 삭제가 아니라 해당 추천의 원본 큐 카드를 그날 추천에서만 제외하며, 다음 날 같은 큐 카드는 다시 추천 후보가 됩니다. 회복 수단 추천은 패스할 수 없습니다(400).
 * @summary 추천 패스
 */
export const passRecommendation = (
  recommendId: number,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<void>(
    { url: `/schedule/recommendations/${recommendId}/pass`, method: 'POST', signal },
    options,
  );
};

export const getPassRecommendationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof passRecommendation>>,
    TError,
    { recommendId: number },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof passRecommendation>>,
  TError,
  { recommendId: number },
  TContext
> => {
  const mutationKey = ['passRecommendation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof passRecommendation>>,
    { recommendId: number }
  > = (props) => {
    const { recommendId } = props ?? {};

    return passRecommendation(recommendId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PassRecommendationMutationResult = NonNullable<
  Awaited<ReturnType<typeof passRecommendation>>
>;

export type PassRecommendationMutationError = ErrorType<unknown>;

/**
 * @summary 추천 패스
 */
export const usePassRecommendation = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof passRecommendation>>,
      TError,
      { recommendId: number },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof passRecommendation>>,
  TError,
  { recommendId: number },
  TContext
> => {
  const mutationOptions = getPassRecommendationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 추천을 수락합니다. 큐 카드 추천은 원본 큐 카드를 핀 카드로 전환하고, 회복 수단 추천은 새 일정을 생성합니다. '기존 큐 카드 유지하기'(keepQueueCard=true) 시 큐 카드를 남긴 채 핀 카드를 복제 생성합니다.
 * @summary 추천 수락
 */
export const acceptRecommendation = (
  recommendId: number,
  recommendationAcceptRequest: BodyType<RecommendationAcceptRequest>,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<RecommendationAcceptResponse>(
    {
      url: `/schedule/recommendations/${recommendId}/accept`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: recommendationAcceptRequest,
      signal,
    },
    options,
  );
};

export const getAcceptRecommendationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptRecommendation>>,
    TError,
    { recommendId: number; data: BodyType<RecommendationAcceptRequest> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptRecommendation>>,
  TError,
  { recommendId: number; data: BodyType<RecommendationAcceptRequest> },
  TContext
> => {
  const mutationKey = ['acceptRecommendation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptRecommendation>>,
    { recommendId: number; data: BodyType<RecommendationAcceptRequest> }
  > = (props) => {
    const { recommendId, data } = props ?? {};

    return acceptRecommendation(recommendId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptRecommendationMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptRecommendation>>
>;
export type AcceptRecommendationMutationBody = BodyType<RecommendationAcceptRequest>;
export type AcceptRecommendationMutationError = ErrorType<unknown>;

/**
 * @summary 추천 수락
 */
export const useAcceptRecommendation = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptRecommendation>>,
      TError,
      { recommendId: number; data: BodyType<RecommendationAcceptRequest> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptRecommendation>>,
  TError,
  { recommendId: number; data: BodyType<RecommendationAcceptRequest> },
  TContext
> => {
  const mutationOptions = getAcceptRecommendationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 특정 큐 카드를 핀 카드로 전환할 후보 시간대를 오늘부터 days일 이내에서 날짜별 1개씩 찾습니다. 후보가 없으면 409로 { canExtendTo14Days, mustChangeDuration } 를 반환합니다. 각 후보의 recommendId 로 기존 수락 API(POST /schedule/recommendations/{recommendId}/accept)를 호출해 핀 전환합니다.
 * @summary 큐 카드 추천 시간대 조회
 */
export const getQueueCardRecommendations = (
  scheduleId: number,
  params?: GetQueueCardRecommendationsParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<GetQueueCardRecommendations200>(
    { url: `/schedule/${scheduleId}/recommendations`, method: 'GET', params, signal },
    options,
  );
};

export const getGetQueueCardRecommendationsQueryKey = (
  scheduleId?: number,
  params?: GetQueueCardRecommendationsParams,
) => {
  return [`/schedule/${scheduleId}/recommendations`, ...(params ? [params] : [])] as const;
};

export const getGetQueueCardRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getQueueCardRecommendations>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  params?: GetQueueCardRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQueueCardRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetQueueCardRecommendationsQueryKey(scheduleId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueueCardRecommendations>>> = ({
    signal,
  }) => getQueueCardRecommendations(scheduleId, params, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!scheduleId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQueueCardRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQueueCardRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQueueCardRecommendations>>
>;
export type GetQueueCardRecommendationsQueryError = ErrorType<unknown>;

export function useGetQueueCardRecommendations<
  TData = Awaited<ReturnType<typeof getQueueCardRecommendations>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  params: undefined | GetQueueCardRecommendationsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQueueCardRecommendations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueueCardRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getQueueCardRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetQueueCardRecommendations<
  TData = Awaited<ReturnType<typeof getQueueCardRecommendations>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  params?: GetQueueCardRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQueueCardRecommendations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueueCardRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getQueueCardRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetQueueCardRecommendations<
  TData = Awaited<ReturnType<typeof getQueueCardRecommendations>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  params?: GetQueueCardRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQueueCardRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 큐 카드 추천 시간대 조회
 */

export function useGetQueueCardRecommendations<
  TData = Awaited<ReturnType<typeof getQueueCardRecommendations>>,
  TError = ErrorType<unknown>,
>(
  scheduleId: number,
  params?: GetQueueCardRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQueueCardRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQueueCardRecommendationsQueryOptions(scheduleId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 빈 시간에 배치된 큐 카드 추천 목록을 조회합니다. 조회 시마다 현재 컨디션·큐 카드·핀 카드 기준으로 재생성됩니다.
 * @summary 추천 목록 조회
 */
export const getRecommendations = (
  params: GetRecommendationsParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<RecommendationListResponse>(
    { url: `/schedule/recommendations`, method: 'GET', params, signal },
    options,
  );
};

export const getGetRecommendationsQueryKey = (params?: GetRecommendationsParams) => {
  return [`/schedule/recommendations`, ...(params ? [params] : [])] as const;
};

export const getGetRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetRecommendationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecommendationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecommendations>>> = ({ signal }) =>
    getRecommendations(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecommendations>>
>;
export type GetRecommendationsQueryError = ErrorType<unknown>;

export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetRecommendationsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetRecommendationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 추천 목록 조회
 */

export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetRecommendationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendations>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRecommendationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 컨디션 탭 바텀시트에 노출할 빈 시간, 컨디션 태그, 추천 일정, 추천 문구를 조회합니다.
 * @summary 컨디션 기반 추천 일정 조회
 */
export const getConditionRecommendations = (
  params: GetConditionRecommendationsParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseConditionRecommendationResponse>(
    { url: `/schedule/recommendations/condition`, method: 'GET', params, signal },
    options,
  );
};

export const getGetConditionRecommendationsQueryKey = (
  params?: GetConditionRecommendationsParams,
) => {
  return [`/schedule/recommendations/condition`, ...(params ? [params] : [])] as const;
};

export const getGetConditionRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getConditionRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetConditionRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConditionRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetConditionRecommendationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConditionRecommendations>>> = ({
    signal,
  }) => getConditionRecommendations(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getConditionRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConditionRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConditionRecommendations>>
>;
export type GetConditionRecommendationsQueryError = ErrorType<unknown>;

export function useGetConditionRecommendations<
  TData = Awaited<ReturnType<typeof getConditionRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetConditionRecommendationsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConditionRecommendations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConditionRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getConditionRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetConditionRecommendations<
  TData = Awaited<ReturnType<typeof getConditionRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetConditionRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConditionRecommendations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConditionRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getConditionRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetConditionRecommendations<
  TData = Awaited<ReturnType<typeof getConditionRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetConditionRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConditionRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 컨디션 기반 추천 일정 조회
 */

export function useGetConditionRecommendations<
  TData = Awaited<ReturnType<typeof getConditionRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: GetConditionRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getConditionRecommendations>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConditionRecommendationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
