/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseMeasurementAverageResponse,
  ApiResponseMeasurementRecordResponse,
  GetAverageRecordsParams,
  GetDailyRecordParams,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 특정 날짜의 컨디션 기록과 수면 기록을 함께 조회합니다.<br>
컨디션 기록은 dateTime의 날짜 기준, 수면 기록은 wakeUpTime의 날짜 기준으로 포함합니다.<br>
YYYY-MM-DD 형식으로 입력하면 됩니다.

 * @summary 하루 기록 목록 조회
 */
export const getDailyRecord = (
  params: GetDailyRecordParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseMeasurementRecordResponse>(
    { url: `/measurements`, method: 'GET', params, signal },
    options,
  );
};

export const getGetDailyRecordQueryKey = (params?: GetDailyRecordParams) => {
  return [`/measurements`, ...(params ? [params] : [])] as const;
};

export const getGetDailyRecordQueryOptions = <
  TData = Awaited<ReturnType<typeof getDailyRecord>>,
  TError = ErrorType<unknown>,
>(
  params: GetDailyRecordParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDailyRecordQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDailyRecord>>> = ({ signal }) =>
    getDailyRecord(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDailyRecord>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDailyRecordQueryResult = NonNullable<Awaited<ReturnType<typeof getDailyRecord>>>;
export type GetDailyRecordQueryError = ErrorType<unknown>;

export function useGetDailyRecord<
  TData = Awaited<ReturnType<typeof getDailyRecord>>,
  TError = ErrorType<unknown>,
>(
  params: GetDailyRecordParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyRecord>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyRecord>>,
          TError,
          Awaited<ReturnType<typeof getDailyRecord>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyRecord<
  TData = Awaited<ReturnType<typeof getDailyRecord>>,
  TError = ErrorType<unknown>,
>(
  params: GetDailyRecordParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyRecord>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDailyRecord>>,
          TError,
          Awaited<ReturnType<typeof getDailyRecord>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDailyRecord<
  TData = Awaited<ReturnType<typeof getDailyRecord>>,
  TError = ErrorType<unknown>,
>(
  params: GetDailyRecordParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 하루 기록 목록 조회
 */

export function useGetDailyRecord<
  TData = Awaited<ReturnType<typeof getDailyRecord>>,
  TError = ErrorType<unknown>,
>(
  params: GetDailyRecordParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDailyRecord>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDailyRecordQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 지정한 기간의 평균 컨디션 점수, Body/Mind 퍼센트, 수면 점수, 수면 시간 평균을 조회합니다.<br>
groupBy 값에 따라 DAY, WEEK, MONTH 단위로 집계합니다.<br>
from과 to는 YYYY-MM-DD 형식으로 입력하면 됩니다.

 * @summary 평균 보기 조회
 */
export const getAverageRecords = (
  params: GetAverageRecordsParams,
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseMeasurementAverageResponse>(
    { url: `/measurements/averages`, method: 'GET', params, signal },
    options,
  );
};

export const getGetAverageRecordsQueryKey = (params?: GetAverageRecordsParams) => {
  return [`/measurements/averages`, ...(params ? [params] : [])] as const;
};

export const getGetAverageRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAverageRecords>>,
  TError = ErrorType<unknown>,
>(
  params: GetAverageRecordsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAverageRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAverageRecordsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAverageRecords>>> = ({ signal }) =>
    getAverageRecords(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAverageRecords>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAverageRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAverageRecords>>
>;
export type GetAverageRecordsQueryError = ErrorType<unknown>;

export function useGetAverageRecords<
  TData = Awaited<ReturnType<typeof getAverageRecords>>,
  TError = ErrorType<unknown>,
>(
  params: GetAverageRecordsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAverageRecords>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAverageRecords>>,
          TError,
          Awaited<ReturnType<typeof getAverageRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAverageRecords<
  TData = Awaited<ReturnType<typeof getAverageRecords>>,
  TError = ErrorType<unknown>,
>(
  params: GetAverageRecordsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAverageRecords>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAverageRecords>>,
          TError,
          Awaited<ReturnType<typeof getAverageRecords>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAverageRecords<
  TData = Awaited<ReturnType<typeof getAverageRecords>>,
  TError = ErrorType<unknown>,
>(
  params: GetAverageRecordsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAverageRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 평균 보기 조회
 */

export function useGetAverageRecords<
  TData = Awaited<ReturnType<typeof getAverageRecords>>,
  TError = ErrorType<unknown>,
>(
  params: GetAverageRecordsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAverageRecords>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAverageRecordsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
