/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Unplan API
 * Unplan Server API Documentation
 * OpenAPI spec version: v1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AlarmSettingRequestDto,
  ApiResponseAlarmSettingResponseDto,
  ApiResponseEmptyTimeSettingResponseDto,
  EmptyTimeSettingRequestDto,
} from '../../model';

import { apiMutator } from '../../mutator/orval-mutator';
import type { ErrorType, BodyType } from '../../mutator/orval-mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getEmptyTimeRecommendSetting = (
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseEmptyTimeSettingResponseDto>(
    { url: `/api/member-settings/empty-time`, method: 'GET', signal },
    options,
  );
};

export const getGetEmptyTimeRecommendSettingQueryKey = () => {
  return [`/api/member-settings/empty-time`] as const;
};

export const getGetEmptyTimeRecommendSettingQueryOptions = <
  TData = Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>, TError, TData>
  >;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEmptyTimeRecommendSettingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>> = ({
    signal,
  }) => getEmptyTimeRecommendSetting(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEmptyTimeRecommendSettingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>
>;
export type GetEmptyTimeRecommendSettingQueryError = ErrorType<unknown>;

export function useGetEmptyTimeRecommendSetting<
  TData = Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
          TError,
          Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEmptyTimeRecommendSetting<
  TData = Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
          TError,
          Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEmptyTimeRecommendSetting<
  TData = Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetEmptyTimeRecommendSetting<
  TData = Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEmptyTimeRecommendSetting>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEmptyTimeRecommendSettingQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateEmptyTimeRecommendSetting = (
  emptyTimeSettingRequestDto: BodyType<EmptyTimeSettingRequestDto>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseEmptyTimeSettingResponseDto>(
    {
      url: `/api/member-settings/empty-time`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: emptyTimeSettingRequestDto,
    },
    options,
  );
};

export const getUpdateEmptyTimeRecommendSettingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>,
    TError,
    { data: BodyType<EmptyTimeSettingRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>,
  TError,
  { data: BodyType<EmptyTimeSettingRequestDto> },
  TContext
> => {
  const mutationKey = ['updateEmptyTimeRecommendSetting'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>,
    { data: BodyType<EmptyTimeSettingRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return updateEmptyTimeRecommendSetting(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEmptyTimeRecommendSettingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>
>;
export type UpdateEmptyTimeRecommendSettingMutationBody = BodyType<EmptyTimeSettingRequestDto>;
export type UpdateEmptyTimeRecommendSettingMutationError = ErrorType<unknown>;

export const useUpdateEmptyTimeRecommendSetting = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>,
      TError,
      { data: BodyType<EmptyTimeSettingRequestDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateEmptyTimeRecommendSetting>>,
  TError,
  { data: BodyType<EmptyTimeSettingRequestDto> },
  TContext
> => {
  const mutationOptions = getUpdateEmptyTimeRecommendSettingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getAlarmSetting = (
  options?: SecondParameter<typeof apiMutator>,
  signal?: AbortSignal,
) => {
  return apiMutator<ApiResponseAlarmSettingResponseDto>(
    { url: `/api/member-settings/alarm-setting`, method: 'GET', signal },
    options,
  );
};

export const getGetAlarmSettingQueryKey = () => {
  return [`/api/member-settings/alarm-setting`] as const;
};

export const getGetAlarmSettingQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlarmSetting>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAlarmSetting>>, TError, TData>>;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAlarmSettingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlarmSetting>>> = ({ signal }) =>
    getAlarmSetting(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAlarmSetting>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAlarmSettingQueryResult = NonNullable<Awaited<ReturnType<typeof getAlarmSetting>>>;
export type GetAlarmSettingQueryError = ErrorType<unknown>;

export function useGetAlarmSetting<
  TData = Awaited<ReturnType<typeof getAlarmSetting>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAlarmSetting>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlarmSetting>>,
          TError,
          Awaited<ReturnType<typeof getAlarmSetting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAlarmSetting<
  TData = Awaited<ReturnType<typeof getAlarmSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAlarmSetting>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAlarmSetting>>,
          TError,
          Awaited<ReturnType<typeof getAlarmSetting>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAlarmSetting<
  TData = Awaited<ReturnType<typeof getAlarmSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAlarmSetting>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetAlarmSetting<
  TData = Awaited<ReturnType<typeof getAlarmSetting>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAlarmSetting>>, TError, TData>>;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAlarmSettingQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateAlarmSetting = (
  alarmSettingRequestDto: BodyType<AlarmSettingRequestDto>,
  options?: SecondParameter<typeof apiMutator>,
) => {
  return apiMutator<ApiResponseAlarmSettingResponseDto>(
    {
      url: `/api/member-settings/alarm-setting`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: alarmSettingRequestDto,
    },
    options,
  );
};

export const getUpdateAlarmSettingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAlarmSetting>>,
    TError,
    { data: BodyType<AlarmSettingRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAlarmSetting>>,
  TError,
  { data: BodyType<AlarmSettingRequestDto> },
  TContext
> => {
  const mutationKey = ['updateAlarmSetting'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAlarmSetting>>,
    { data: BodyType<AlarmSettingRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return updateAlarmSetting(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAlarmSettingMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAlarmSetting>>
>;
export type UpdateAlarmSettingMutationBody = BodyType<AlarmSettingRequestDto>;
export type UpdateAlarmSettingMutationError = ErrorType<unknown>;

export const useUpdateAlarmSetting = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAlarmSetting>>,
      TError,
      { data: BodyType<AlarmSettingRequestDto> },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAlarmSetting>>,
  TError,
  { data: BodyType<AlarmSettingRequestDto> },
  TContext
> => {
  const mutationOptions = getUpdateAlarmSettingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
